---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop getting-started
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm getting-started
      ignore_errors: yes

    - name: remove getting-started-image
      command: docker rmi salah9999/getting-started
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t salah9999/getting-started .

    - name: Push Image to dockerhub
      command: docker push salah9999/getting-started

    - name: run container
      command: docker run -d --name web-container -p 5000:80 salah9999/getting-started