- name: "Build and deploy a container with Ansible"
  hosts: 54.226.98.29  # Use the actual IP address of your AWS instance
  remote_user: ec2-user  # Specify the correct username
  tasks:
    - name: Stop and remove existing container
      docker_container:
        name: getting-started
        state: stopped
        force_kill: yes
        remove: yes

    - name: Build Docker image using the Dockerfile
      command: docker build -t salah9999/getting-started .

    - name: Run container
      command: docker run -d --name getting-started -p 5000:80 salah9999/getting-started
