---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop getting-started
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm getting-started
      ignore_errors: yes

    - name: remove getting-started-image
      command: docker rmi salah9999/getting-started
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t salah9999/getting-started .

    - name: Log in to DockerHub
      command: docker login -u salah9999 -p K2Ga5qa^AG6j58W
      ignore_errors: yes

    - name: Push Image to DockerHub
      command: docker push salah9999/getting-started

    - name: Log out from DockerHub
      command: docker logout
      ignore_errors: yes

    - name: run container
      command: docker run -d --name getting-started -p 5000:80 salah9999/getting-started
